### ISSUE TITLE
Staging environment

### ISSUE THREAD

**Issue by tmattio** [ocurrent/ocaml-docs-ci#87]
Having a URL that points to a staging version of the pipeline will allow us to test changes on staging.ocaml.org before pushing them in production.

See https://github.com/ocaml/infrastructure/issues/18

**Comment by tmattio** [comment]
Note that a temporary staging environment is available at: [docs.ocamllabs.io](http://docs.ocamllabs.io/).
To finalize https://github.com/ocaml/infrastructure/issues/18 we'd need to have a better idea of the requirements for the machine. For that we need to:
- make the changes to only build a subset of the packages
- run the pipeline on this subset and measure the memory and CPU usage to get the requirements.

**Comment by tmcgilchrist** [comment]
Staging environment setup on [docs-staging.sw.ocaml.org](https://docs-staging.sw.ocaml.org/) using [deploy.ci.ocaml.org](https://deploy.ci.ocaml.org/?repo=ocurrent/ocaml-docs-ci&) for the docs pipeline. Note the staging.ocaml.org environment is not currently using the output of the pipeline. We need a way of validating the output of the pipeline, without breaking `live`. @sabine

**Comment by TheLortex** [comment]
To limit the number of tracked packages, you can use the `filter` and `limit` options.
For example `--filter mirage,uri --limit 2` would select the 2 last versions of mirage and uri (and their dependency cone).

**Comment by tmcgilchrist** [comment]
Thanks @TheLortex I've setup the staging environment with `--limit=1` for the whole opam universe to see how much disk space it takes. With too many versions I'm quickly running out of space.

**Comment by tmcgilchrist** [comment]
Running staging pipeline with `limit=1` gives a full build of everything without going over the disk space budget. I'm working through the solver and build failures to get a sense of what is an expected failure. 

WIP PR for adding more README documentation https://github.com/ocurrent/ocaml-docs-ci/pull/100

**Comment by tmcgilchrist** [comment]
This can be closed. We have a working staging pipeline setup on https://staging.docs.ci.ocaml.org
