### ISSUE TITLE
Application and Operational Metrics

### ISSUE THREAD

**Issue by tmcgilchrist** [ocurrent/ocaml-docs-ci#94]
`ocaml-docs-ci` should report on application and operational level metrics via prometheus/grafana. 
<img width="911" alt="Screenshot 2023-05-19 at 12 16 18" src="https://github.com/ocurrent/ocaml-docs-ci/assets/170937/8ab502f5-b3d3-493e-ab7a-865c2caa1271">

- [x] Production dashboard in grafana for https://docs.ci.ocaml.org
- [x] Staging dashboard in grafana for https://staging.docs.ci.ocaml.org
- [x] Setup ocluster connection to export stats (it already supports prometheus)
- [x] Add stat exports to docs-ci solver
- [x] Add stats export to [monitor.ml](https://github.com/ocurrent/ocaml-docs-ci/blob/main/src/lib/monitor.mli).
- [x] Setup ocurrent to export stats (it already supports prometheus)
- [ ] Add host monitoring for `storage` and `web server` containers. Alert on disk space usage over 80%.
- [x] Add ocurrent support for exporting Node creation/update/destroy metrics (as a proxy for graph size)

Non-exhaustive list of tasks to cover the monitoring of `ocaml-docs-ci` application.

**Comment by tmcgilchrist** [comment]
@tmattio the only outstanding work is to add `Alert on disk space usage over 80%.`

**Comment by tmattio** [comment]
Operational metrics were added to the Grafana dashboard and we agreed that they are sufficient to monitor the services for the time being. We might add more in the future if we see that more metrics are necessary.
